### ISSUE TITLE
Need simple "like" functionality

### ISSUE THREAD

**Issue by secretrobotron** [flukeout/wobbl#1]
Many of the images in the gallery deserve a token of appreciation. Implement a "like" button!

**Comment by flukeout** [comment]
Definitely! I'm thinking of a very lightweight solution that would let you like something anonymously and just keep track in localstorage the ids of the ones you liked so it wouldn't let you (super easily) like something a bunch of times.

**Comment by flukeout** [comment]
Added. Try it out (although gallery is empty) so add a couple items first.

![image](https://cloud.githubusercontent.com/assets/25212/9978797/4cc3e886-5efe-11e5-8571-71062c238485.png)
